// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SandwichManagement.Migrations
{
    [DbContext(typeof(SandwichContext))]
    [Migration("20221222030828_InitDatabase")]
    partial class InitDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sandwich", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Sandwiches");
                });

            modelBuilder.Entity("SandwichDescription", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("SandwichId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SandwichId");

                    b.ToTable("SandwichDescriptions");
                });

            modelBuilder.Entity("SandwichDescription", b =>
                {
                    b.HasOne("Sandwich", "Sandwich")
                        .WithMany("SandwichDescriptions")
                        .HasForeignKey("SandwichId");

                    b.Navigation("Sandwich");
                });

            modelBuilder.Entity("Sandwich", b =>
                {
                    b.Navigation("SandwichDescriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
